// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUGKxkegmQrJfVYf_-JPE-4sp-BiDChI',
    appId: '1:668776581073:web:bfd8b79d507bafcd3dc2f0',
    messagingSenderId: '668776581073',
    projectId: 'app-analyzer-ed257',
    authDomain: 'app-analyzer-ed257.firebaseapp.com',
    storageBucket: 'app-analyzer-ed257.firebasestorage.app',
    measurementId: 'G-5D1N3DNW66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAicmH4Dnd-aspoaGFwjSz4vgGG1IeHIU8',
    appId: '1:668776581073:android:d2879122369b59473dc2f0',
    messagingSenderId: '668776581073',
    projectId: 'app-analyzer-ed257',
    storageBucket: 'app-analyzer-ed257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Y6gYiwb4bpwGf9iXHkFxvTQUBxauugI',
    appId: '1:668776581073:ios:17fd015caa3f02303dc2f0',
    messagingSenderId: '668776581073',
    projectId: 'app-analyzer-ed257',
    storageBucket: 'app-analyzer-ed257.firebasestorage.app',
    iosBundleId: 'com.example.appAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Y6gYiwb4bpwGf9iXHkFxvTQUBxauugI',
    appId: '1:668776581073:ios:17fd015caa3f02303dc2f0',
    messagingSenderId: '668776581073',
    projectId: 'app-analyzer-ed257',
    storageBucket: 'app-analyzer-ed257.firebasestorage.app',
    iosBundleId: 'com.example.appAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvUGKxkegmQrJfVYf_-JPE-4sp-BiDChI',
    appId: '1:668776581073:web:a6e8f24bcba03dc43dc2f0',
    messagingSenderId: '668776581073',
    projectId: 'app-analyzer-ed257',
    authDomain: 'app-analyzer-ed257.firebaseapp.com',
    storageBucket: 'app-analyzer-ed257.firebasestorage.app',
    measurementId: 'G-W4RGS1Y7G4',
  );

}